
export const ITEM_ADDED = 'ITEM_ADDED';
export type ITEM_ADDED = typeof ITEM_ADDED

export const ITEM_DELETED = 'ITEM_DELETED'
export type ITEM_DELETED = typeof ITEM_DELETED

export const ITEM_FILTERED = 'ITEM_FILTERED'
export type ITEM_FILTERED = typeof ITEM_FILTERED


export const ITEM_STATUS_CHANGED_ACTIVE = 'ITEM_STATUS_CHANGED_ACTIVE'
export type ITEM_STATUS_CHANGED_ACTIVE = typeof ITEM_STATUS_CHANGED_ACTIVE


export const ITEM_STATUS_CHANGED_DELETED = 'ITEM_STATUS_CHANGED_DELETED'
export type ITEM_STATUS_CHANGED_DELETED = typeof ITEM_STATUS_CHANGED_DELETED