
export const ITEM_ADDED = 'ITEM_ADDED';
export type ITEM_ADDED = typeof ITEM_ADDED

export const ITEM_DELETED = 'ITEM_DELETED'
export type ITEM_DELETED = typeof ITEM_DELETED


export const ACTIVE_SWITCHED = 'ACTIVE_SWITCHED'
export type ACTIVE_SWITCHED = typeof ACTIVE_SWITCHED


export const ITEMS_LOADED_FROM_LOCAL_STORAGE = 'ITEMS_LOADED_FROM_LOCAL_STORAGE'
export type ITEMS_LOADED_FROM_LOCAL_STORAGE = typeof ITEMS_LOADED_FROM_LOCAL_STORAGE